### ISSUE TITLE
Does this work on Windows 10?

### ISSUE THREAD

**Issue by SudoHenk** [livepeer/LivepeerDesktop#10]
Hi, I'm very intrigued by the concept of Livepeer (I was actually thinking of a combination between blockchain incentives in combination with a decentralized video platform, hence I started googling).

I wanted to try the desktop Client on Windows 10, but once I startup the application I get the following error. It does show a GUI, but it keeps hanging at "Starting Livepeer Node", with a few CPU hungy processes running in the background.

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: spawn C:\Users\<USERNAME>\LivepeerDesktop\node_modules/livepeer-static/bin\win32\x64\livepeer.exe ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[OK]
```

**Comment by dob** [comment]
Thanks for checking it out. Livepeer does not yet work on Windows, as the golang Livepeer node needs to be updated to support windows paths and os calls. It's being tracked here:

https://github.com/livepeer/LivepeerDesktop/issues/4
https://github.com/livepeer/go-livepeer/issues/112

If you have any go development expertise, we'd welcome help on updating the node itself. It may not be too far off.
